#!/usr/bin/php
<?php
# returns a short url for argument
# using linkst.rip API

if (count($argv) < 2) {
    die("url needs to be provided as argument.".PHP_EOL);
}

$url = $argv[1];

$curl = curl_init("https://linkst.rip/api/newLink?url=$url");

curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$response = curl_exec($curl);
curl_close($curl);

$json = json_decode($response);

echo $json->success ? $json->url : $json->error;

exit(PHP_EOL);
