#!/usr/bin/php
<?php

if (count($argv) < 2) {
    die("url needs to be provided as argument.".PHP_EOL);
}

$url = $argv[1];

if (!filter_var($url, FILTER_VALIDATE_URL)) {
    die("invalid url.".PHP_EOL);
}

$curl = curl_init("https://linkst.rip/api/newLink?url=$url");

curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$response = curl_exec($curl);
curl_close($curl);
echo json_decode($response)->url;

die(PHP_EOL);
